### ISSUE TITLE
read_all_to_vec reads in only a fraction of the file if there is more than one channel

### ISSUE THREAD

**Issue by johannes-mueller** [Xeiron/sndfile.rs#1]
## Expected behavior
When reading a sample file with n channels and m samples (i.e. frames) you would expect `SndFileIO::read_all_to_vec()` return a Vec with lenght n*m samples (m for each channel). So for a stereo file one second long at a sample rate of 48kHz you would expect 1s * 48000kHz * 2 = 96000 samples (48000 for each channel)

## Observed behavior
You actually get a sample of the length m, so for a stereo sample, half the length

**Comment by tuxzz** [comment]
Your pull request has been merged. Thanks for your contribution.
The new published version is 0.0.4.
